---

- name: install required packages
  package:
    name: '{{ item }}'
    state: present
  loop: '{{ graphite_requirements }}'
  register: graphite_register_rpms_installed
  until: graphite_register_rpms_installed is success
  retries: 10
  delay: 2

- name: install graphite from pip
  environment:
    PATH: '/opt/rh/rh-python36/root/usr/bin:{{ ansible_env.PATH }}'
    LD_LIBRARY_PATH: '/opt/rh/rh-python36/root/usr/lib64'
    MANPATH: '/opt/rh/rh-python36/root/usr/share/man:'
    PKG_CONFIG_PATH: '/opt/rh/rh-python36/root/usr/lib64/pkgconfig'
    XDG_DATA_DIRS: '/opt/rh/rh-python36/root/usr/share:/usr/local/share:/usr/share'
  vars:
    ansible_python_interpreter: /opt/rh/rh-python36/root/usr/bin/python
  pip:
    executable: "/opt/rh/rh-python36/root/usr/bin/pip"
    virtualenv_command: "/opt/rh/rh-python36/root/usr/bin/virtualenv"
    state: present
    name: "{{ item }}"
  loop: '{{ pip_packages }}'
  register: graphite_register_pip_installed
  until: graphite_register_pip_installed is success
  retries: 10
  delay: 2
